[dependencies]
rnix = "*"
rowan = "0.12.6" # follows rnix

[package]
authors = ["Kevin Amado <kamadorueda@gmail.com>"]
description = "The Uncompromising Nix Code Formatter"
edition = "2021"
name = "alejandra_engine"
repository = "https://github.com/kamadorueda/alejandra"
version = "0.4.0"
